// Adjektiv-data for Deutschwelt — generert av regler + håndplukket liste (A1–B1).
// a=adjektiv, n=norsk, l=nivå, c=komparativ, s=superlativ (stamme uten -en), cm/sm=med røde markører ‹ ›,
// ps=stamme før endelse, c2/s2=alternativ form, ng=ingen gradbøying, ind=ubøyelig, nd=viel/wenig, t=brukes i endelsestreneren
var dwAdj=[
{"a":"ähnlich","n":"lik, lignende","l":"B1","c":"ähnlicher","s":"ähnlichst","e":"Die Schwestern sehen sich ähnlich.","en":"Søstrene ligner hverandre."},
{"a":"alt","n":"gammel","l":"A1","c":"älter","s":"ältest","cm":"‹ä›lter","sm":"‹ä›ltest","t":1,"e":"Mein Opa ist sehr alt.","en":"Bestefaren min er veldig gammel."},
{"a":"ängstlich","n":"engstelig","l":"B1","c":"ängstlicher","s":"ängstlichst","e":"Meine Katze ist ängstlich.","en":"Katten min er engstelig."},
{"a":"arm","n":"fattig","l":"A2","c":"ärmer","s":"ärmst","cm":"‹ä›rmer","sm":"‹ä›rmst","e":"Viele Menschen sind arm.","en":"Mange mennesker er fattige."},
{"a":"attraktiv","n":"attraktiv","l":"B1","c":"attraktiver","s":"attraktivst","e":"Das Angebot ist attraktiv.","en":"Tilbudet er attraktivt."},
{"a":"beige","n":"beige","l":"A2","ind":1,"e":"Mein Mantel ist beige.","en":"Frakken min er beige."},
{"a":"bekannt","n":"kjent","l":"A2","c":"bekannter","s":"bekanntest","e":"Das Lied ist bekannt.","en":"Sangen er kjent."},
{"a":"beliebt","n":"populær, avholdt","l":"B1","c":"beliebter","s":"beliebtest","e":"Das ist ein beliebtes Spiel.","en":"Det er et populært spill."},
{"a":"bequem","n":"komfortabel","l":"A2","c":"bequemer","s":"bequemst","t":1,"e":"Das Sofa ist bequem.","en":"Sofaen er komfortabel."},
{"a":"berühmt","n":"berømt","l":"A2","c":"berühmter","s":"berühmtest","e":"Er ist ein berühmter Sänger.","en":"Han er en berømt sanger."},
{"a":"billig","n":"billig","l":"A1","c":"billiger","s":"billigst","t":1,"e":"Die Hose war billig.","en":"Buksa var billig."},
{"a":"bitter","n":"bitter","l":"B1","c":"bitterer","s":"bitterst","e":"Die Schokolade ist bitter.","en":"Sjokoladen er bitter."},
{"a":"blau","n":"blå","l":"A1","ng":1,"e":"Der Himmel ist blau.","en":"Himmelen er blå."},
{"a":"blond","n":"blond","l":"A2","c":"blonder","s":"blondest","e":"Er hat blonde Haare.","en":"Han har blondt hår."},
{"a":"böse","n":"slem, ond","l":"A2","c":"böser","s":"bösest","e":"Der Hund ist nicht böse.","en":"Hunden er ikke slem."},
{"a":"braun","n":"brun","l":"A1","ng":1,"e":"Mein Hund ist braun.","en":"Hunden min er brun."},
{"a":"breit","n":"bred","l":"A2","c":"breiter","s":"breitest","t":1,"e":"Die Straße ist breit.","en":"Gata er bred."},
{"a":"bunt","n":"fargerik, broket","l":"A2","c":"bunter","s":"buntest","t":1,"e":"Sie hat bunte Socken.","en":"Hun har fargerike sokker."},
{"a":"dankbar","n":"takknemlig","l":"B1","c":"dankbarer","s":"dankbarst","e":"Ich bin dir sehr dankbar.","en":"Jeg er deg veldig takknemlig."},
{"a":"deutlich","n":"tydelig","l":"B1","c":"deutlicher","s":"deutlichst","e":"Sprich bitte deutlich!","en":"Snakk tydelig, vær så snill!"},
{"a":"dick","n":"tykk","l":"A1","c":"dicker","s":"dickst","t":1,"e":"Das Buch ist sehr dick.","en":"Boka er veldig tykk."},
{"a":"dringend","n":"presserende, hastende","l":"B1","c":"dringender","s":"dringendst","e":"Das ist ein dringender Fall.","en":"Det er en presserende sak."},
{"a":"dumm","n":"dum","l":"A1","c":"dümmer","s":"dümmst","cm":"d‹ü›mmer","sm":"d‹ü›mmst","e":"Das war eine dumme Idee.","en":"Det var en dum idé."},
{"a":"dunkel","n":"mørk","l":"A2","c":"dunkler","s":"dunkelst","ps":"dunkl","t":1,"e":"Draußen ist es schon dunkel.","en":"Ute er det allerede mørkt."},
{"a":"dünn","n":"tynn","l":"A1","c":"dünner","s":"dünnst","t":1,"e":"Sie trägt einen dünnen Pullover.","en":"Hun har på seg en tynn genser."},
{"a":"durstig","n":"tørst","l":"A2","c":"durstiger","s":"durstigst","e":"Bist du auch durstig?","en":"Er du også tørst?"},
{"a":"echt","n":"ekte","l":"A2","c":"echter","s":"echtest","e":"Das ist echtes Leder.","en":"Det er ekte skinn."},
{"a":"ehrlich","n":"ærlig","l":"A2","c":"ehrlicher","s":"ehrlichst","e":"Ich bin ehrlich zu dir.","en":"Jeg er ærlig mot deg."},
{"a":"eigen","n":"egen","l":"B1","c":"eigener","s":"eigenst","e":"Ich habe ein eigenes Zimmer.","en":"Jeg har mitt eget rom."},
{"a":"einfach","n":"enkel","l":"A1","c":"einfacher","s":"einfachst","t":1,"e":"Das ist ganz einfach.","en":"Det er helt enkelt."},
{"a":"einzig","n":"eneste","l":"B1","ng":1,"e":"Das ist die einzige Lösung.","en":"Det er den eneste løsningen."},
{"a":"eng","n":"trang","l":"B1","c":"enger","s":"engst","e":"Die Hose ist zu eng.","en":"Buksa er for trang."},
{"a":"erfolgreich","n":"suksessfull","l":"B1","c":"erfolgreicher","s":"erfolgreichst","e":"Sie ist eine erfolgreiche Ärztin.","en":"Hun er en suksessfull lege."},
{"a":"ernst","n":"alvorlig","l":"B1","c":"ernster","s":"ernstest","e":"Das ist ein ernstes Problem.","en":"Det er et alvorlig problem."},
{"a":"falsch","n":"feil, falsk","l":"A1","c":"falscher","s":"falschest","e":"Die Antwort ist falsch.","en":"Svaret er feil."},
{"a":"faul","n":"lat","l":"A2","c":"fauler","s":"faulst","e":"Heute bin ich faul.","en":"I dag er jeg lat."},
{"a":"fern","n":"fjern","l":"B1","c":"ferner","s":"fernst","e":"Das ist noch in ferner Zukunft.","en":"Det er ennå i en fjern framtid."},
{"a":"fertig","n":"ferdig","l":"A1","ng":1,"e":"Ich bin fertig.","en":"Jeg er ferdig."},
{"a":"fest","n":"fast","l":"B1","c":"fester","s":"festest","e":"Das Seil ist fest.","en":"Tauet er fast."},
{"a":"feucht","n":"fuktig","l":"B1","c":"feuchter","s":"feuchtest","e":"Die Luft ist feucht.","en":"Lufta er fuktig."},
{"a":"flach","n":"flat","l":"A2","c":"flacher","s":"flachst","e":"Das Land ist flach.","en":"Landet er flatt."},
{"a":"fleißig","n":"flittig","l":"A2","c":"fleißiger","s":"fleißigst","e":"Die Schüler sind fleißig.","en":"Elevene er flittige."},
{"a":"frei","n":"fri","l":"A2","c":"freier","s":"freiest","e":"Ist dieser Platz frei?","en":"Er denne plassen ledig?"},
{"a":"fremd","n":"fremmed","l":"B1","c":"fremder","s":"fremdest","e":"Die Stadt ist mir fremd.","en":"Byen er fremmed for meg."},
{"a":"freundlich","n":"vennlig","l":"A1","c":"freundlicher","s":"freundlichst","e":"Die Verkäuferin ist freundlich.","en":"Selgeren er vennlig."},
{"a":"frisch","n":"frisk, fersk","l":"A2","c":"frischer","s":"frischest","e":"Das Brot ist frisch.","en":"Brødet er ferskt."},
{"a":"froh","n":"glad","l":"A2","c":"froher","s":"frohest","e":"Ich bin froh.","en":"Jeg er glad."},
{"a":"früh","n":"tidlig","l":"A1","c":"früher","s":"frühest","e":"Ich stehe früh auf.","en":"Jeg står tidlig opp."},
{"a":"gefährlich","n":"farlig","l":"A2","c":"gefährlicher","s":"gefährlichst","e":"Der Weg ist gefährlich.","en":"Veien er farlig."},
{"a":"gelb","n":"gul","l":"A1","ng":1,"e":"Die Sonne ist gelb.","en":"Sola er gul."},
{"a":"gemeinsam","n":"felles","l":"B1","c":"gemeinsamer","s":"gemeinsamst","e":"Wir haben ein gemeinsames Hobby.","en":"Vi har en felles hobby."},
{"a":"gemütlich","n":"koselig","l":"A2","c":"gemütlicher","s":"gemütlichst","e":"Das Café ist gemütlich.","en":"Kafeen er koselig."},
{"a":"genau","n":"nøyaktig","l":"A2","c":"genauer","s":"genauest","e":"Die Uhr ist genau.","en":"Klokka er nøyaktig."},
{"a":"gesund","n":"frisk, sunn","l":"A1","c":"gesünder","s":"gesündest","cm":"ges‹ü›nder","sm":"ges‹ü›ndest","c2":"gesunder","s2":"gesundest","e":"Obst ist gesund.","en":"Frukt er sunt."},
{"a":"glatt","n":"glatt","l":"B1","c":"glätter","s":"glättest","cm":"gl‹ä›tter","sm":"gl‹ä›ttest","c2":"glatter","s2":"glattest","e":"Die Straße ist glatt.","en":"Veien er glatt."},
{"a":"glücklich","n":"lykkelig, heldig","l":"A1","c":"glücklicher","s":"glücklichst","e":"Wir sind sehr glücklich.","en":"Vi er veldig lykkelige."},
{"a":"grau","n":"grå","l":"A1","ng":1,"e":"Der Himmel ist heute grau.","en":"Himmelen er grå i dag."},
{"a":"groß","n":"stor","l":"A1","c":"größer","s":"größt","cm":"‹größer›","sm":"‹größt›","t":1,"e":"Berlin ist eine große Stadt.","en":"Berlin er en stor by."},
{"a":"grün","n":"grønn","l":"A1","ng":1,"e":"Das Gras ist grün.","en":"Gresset er grønt."},
{"a":"günstig","n":"gunstig, rimelig","l":"A2","c":"günstiger","s":"günstigst","e":"Das ist ein günstiges Angebot.","en":"Det er et gunstig tilbud."},
{"a":"gut","n":"god","l":"A1","c":"besser","s":"best","cm":"‹besser›","sm":"‹best›","t":1,"e":"Das Essen ist gut.","en":"Maten er god."},
{"a":"hart","n":"hard","l":"A2","c":"härter","s":"härtest","cm":"h‹ä›rter","sm":"h‹ä›rtest","e":"Das Brot ist hart.","en":"Brødet er hardt."},
{"a":"hässlich","n":"stygg","l":"A2","c":"hässlicher","s":"hässlichst","t":1,"e":"Die Tapete ist hässlich.","en":"Tapetet er stygt."},
{"a":"häufig","n":"hyppig","l":"B1","c":"häufiger","s":"häufigst","e":"Das ist ein häufiger Fehler.","en":"Det er en hyppig feil."},
{"a":"heiter","n":"lystig, oppklarnet","l":"B1","c":"heiterer","s":"heiterst","e":"Sie ist ein heiterer Mensch.","en":"Hun er et lystig menneske."},
{"a":"heiß","n":"het, varm","l":"A1","c":"heißer","s":"heißest","t":1,"e":"Der Tee ist noch heiß.","en":"Teen er fortsatt varm."},
{"a":"hell","n":"lys","l":"A2","c":"heller","s":"hellst","t":1,"e":"Mein Zimmer ist hell.","en":"Rommet mitt er lyst."},
{"a":"herrlich","n":"herlig","l":"B1","c":"herrlicher","s":"herrlichst","e":"Wir hatten herrliches Wetter.","en":"Vi hadde herlig vær."},
{"a":"hilfsbereit","n":"hjelpsom","l":"B1","c":"hilfsbereiter","s":"hilfsbereitest","e":"Meine Nachbarn sind hilfsbereit.","en":"Naboene mine er hjelpsomme."},
{"a":"hoch","n":"høy","l":"A1","c":"höher","s":"höchst","cm":"‹höher›","sm":"‹höchst›","ps":"hoh","t":1,"e":"Der Berg ist sehr hoch.","en":"Fjellet er veldig høyt."},
{"a":"höflich","n":"høflig","l":"A2","c":"höflicher","s":"höflichst","e":"Sei bitte höflich!","en":"Vær høflig, vær så snill!"},
{"a":"hübsch","n":"pen","l":"A2","c":"hübscher","s":"hübschest","e":"Das ist ein hübsches Mädchen.","en":"Det er ei pen jente."},
{"a":"hungrig","n":"sulten","l":"A1","c":"hungriger","s":"hungrigst","e":"Ich bin hungrig.","en":"Jeg er sulten."},
{"a":"intelligent","n":"intelligent","l":"A2","c":"intelligenter","s":"intelligentest","e":"Er ist sehr intelligent.","en":"Han er veldig intelligent."},
{"a":"interessant","n":"interessant","l":"A1","c":"interessanter","s":"interessantest","t":1,"e":"Das Buch ist interessant.","en":"Boka er interessant."},
{"a":"jung","n":"ung","l":"A1","c":"jünger","s":"jüngst","cm":"j‹ü›nger","sm":"j‹ü›ngst","e":"Meine Schwester ist noch jung.","en":"Søsteren min er ennå ung."},
{"a":"kalt","n":"kald","l":"A1","c":"kälter","s":"kältest","cm":"k‹ä›lter","sm":"k‹ä›ltest","t":1,"e":"Im Winter ist es kalt.","en":"Om vinteren er det kaldt."},
{"a":"klein","n":"liten","l":"A1","c":"kleiner","s":"kleinst","t":1,"e":"Wir haben einen kleinen Hund.","en":"Vi har en liten hund."},
{"a":"klug","n":"klok","l":"A2","c":"klüger","s":"klügst","cm":"kl‹ü›ger","sm":"kl‹ü›gst","e":"Sie ist eine kluge Schülerin.","en":"Hun er en klok elev."},
{"a":"komisch","n":"rar, komisk","l":"A2","c":"komischer","s":"komischst","e":"Das klingt komisch.","en":"Det høres rart ut."},
{"a":"kompliziert","n":"komplisert","l":"B1","c":"komplizierter","s":"kompliziertest","e":"Die Regel ist kompliziert.","en":"Regelen er komplisert."},
{"a":"kostenlos","n":"gratis","l":"A2","ng":1,"e":"Das Eis ist kostenlos.","en":"Isen er gratis."},
{"a":"kräftig","n":"kraftig","l":"B1","c":"kräftiger","s":"kräftigst","e":"Er hat kräftige Arme.","en":"Han har kraftige armer."},
{"a":"krank","n":"syk","l":"A1","c":"kränker","s":"kränkst","cm":"kr‹ä›nker","sm":"kr‹ä›nkst","e":"Mein Bruder ist krank.","en":"Broren min er syk."},
{"a":"kritisch","n":"kritisk","l":"B1","c":"kritischer","s":"kritischst","e":"Sie ist sehr kritisch.","en":"Hun er veldig kritisk."},
{"a":"kühl","n":"kjølig","l":"A2","c":"kühler","s":"kühlst","e":"Das Wasser ist angenehm kühl.","en":"Vannet er behagelig kjølig."},
{"a":"kurz","n":"kort","l":"A1","c":"kürzer","s":"kürzest","cm":"k‹ü›rzer","sm":"k‹ü›rzest","t":1,"e":"Die Pause ist leider kurz.","en":"Pausen er dessverre kort."},
{"a":"lang","n":"lang","l":"A1","c":"länger","s":"längst","cm":"l‹ä›nger","sm":"l‹ä›ngst","t":1,"e":"Der Film ist sehr lang.","en":"Filmen er veldig lang."},
{"a":"langsam","n":"langsom","l":"A1","c":"langsamer","s":"langsamst","t":1,"e":"Mein Computer ist langsam.","en":"Datamaskinen min er treg."},
{"a":"langweilig","n":"kjedelig","l":"A1","c":"langweiliger","s":"langweiligst","t":1,"e":"Der Unterricht war langweilig.","en":"Timen var kjedelig."},
{"a":"laut","n":"høylytt, høy (om lyd)","l":"A2","c":"lauter","s":"lautest","t":1,"e":"Die Musik ist zu laut.","en":"Musikken er for høy."},
{"a":"lebendig","n":"levende","l":"B1","c":"lebendiger","s":"lebendigst","e":"Die Stadt ist sehr lebendig.","en":"Byen er veldig levende."},
{"a":"lecker","n":"deilig, god (om mat)","l":"A1","c":"leckerer","s":"leckerst","e":"Die Pizza ist lecker.","en":"Pizzaen er deilig."},
{"a":"leer","n":"tom","l":"A2","c":"leerer","s":"leerst","t":1,"e":"Das Glas ist leer.","en":"Glasset er tomt."},
{"a":"leicht","n":"lett","l":"A1","c":"leichter","s":"leichtest","t":1,"e":"Die Aufgabe ist leicht.","en":"Oppgaven er lett."},
{"a":"leise","n":"stille, lav (om lyd)","l":"A2","c":"leiser","s":"leisest","e":"Bitte sei leise!","en":"Vær så snill å være stille!"},
{"a":"lieb","n":"snill, kjær","l":"A1","c":"lieber","s":"liebst","e":"Das ist ein lieber Hund.","en":"Det er en snill hund."},
{"a":"lila","n":"lilla","l":"A1","ind":1,"e":"Sie trägt eine lila Jacke.","en":"Hun har på seg en lilla jakke."},
{"a":"locker","n":"løs, avslappet","l":"B1","c":"lockerer","s":"lockerst","e":"Die Schraube ist locker.","en":"Skruen er løs."},
{"a":"lustig","n":"morsom","l":"A1","c":"lustiger","s":"lustigst","e":"Der Film war lustig.","en":"Filmen var morsom."},
{"a":"mild","n":"mild","l":"B1","c":"milder","s":"mildest","e":"Der Winter ist mild.","en":"Vinteren er mild."},
{"a":"modern","n":"moderne","l":"A2","c":"moderner","s":"modernst","t":1,"e":"Das Haus ist sehr modern.","en":"Huset er veldig moderne."},
{"a":"möglich","n":"mulig","l":"A2","c":"möglicher","s":"möglichst","e":"Das ist leider nicht möglich.","en":"Det er dessverre ikke mulig."},
{"a":"müde","n":"trøtt","l":"A1","c":"müder","s":"müdest","e":"Ich bin müde.","en":"Jeg er trøtt."},
{"a":"mutig","n":"modig","l":"A2","c":"mutiger","s":"mutigst","e":"Du bist ein mutiger Junge.","en":"Du er en modig gutt."},
{"a":"nah","n":"nær","l":"A2","c":"näher","s":"nächst","cm":"‹näher›","sm":"‹nächst›","e":"Die Schule ist ganz nah.","en":"Skolen er helt i nærheten."},
{"a":"nass","n":"våt","l":"A2","c":"nässer","s":"nässest","cm":"n‹ä›sser","sm":"n‹ä›ssest","c2":"nasser","s2":"nassest","e":"Meine Haare sind nass.","en":"Håret mitt er vått."},
{"a":"nervös","n":"nervøs","l":"A2","c":"nervöser","s":"nervösest","e":"Vor dem Test bin ich nervös.","en":"Før prøven er jeg nervøs."},
{"a":"nett","n":"hyggelig","l":"A1","c":"netter","s":"nettest","e":"Der Lehrer ist sehr nett.","en":"Læreren er veldig hyggelig."},
{"a":"neu","n":"ny","l":"A1","c":"neuer","s":"neuest","t":1,"e":"Ich habe ein neues Handy.","en":"Jeg har en ny mobil."},
{"a":"neugierig","n":"nysgjerrig","l":"A2","c":"neugieriger","s":"neugierigst","e":"Kinder sind neugierig.","en":"Barn er nysgjerrige."},
{"a":"niedrig","n":"lav","l":"A2","c":"niedriger","s":"niedrigst","e":"Der Tisch ist niedrig.","en":"Bordet er lavt."},
{"a":"normal","n":"normal","l":"A2","c":"normaler","s":"normalst","e":"Das ist ganz normal.","en":"Det er helt normalt."},
{"a":"nötig","n":"nødvendig","l":"B1","c":"nötiger","s":"nötigst","e":"Das ist nicht nötig.","en":"Det er ikke nødvendig."},
{"a":"offen","n":"åpen","l":"A2","c":"offener","s":"offenst","e":"Die Tür ist offen.","en":"Døra er åpen."},
{"a":"offiziell","n":"offisiell","l":"B1","c":"offizieller","s":"offiziellst","e":"Das ist ein offizieller Brief.","en":"Det er et offisielt brev."},
{"a":"orange","n":"oransje","l":"A1","ind":1,"e":"Ich mag das orange Hemd.","en":"Jeg liker den oransje skjorta."},
{"a":"ordentlich","n":"ordentlig","l":"B1","c":"ordentlicher","s":"ordentlichst","e":"Dein Zimmer ist ordentlich.","en":"Rommet ditt er ryddig."},
{"a":"peinlich","n":"pinlig","l":"B1","c":"peinlicher","s":"peinlichst","e":"Das ist mir peinlich.","en":"Det er pinlig for meg."},
{"a":"persönlich","n":"personlig","l":"B1","c":"persönlicher","s":"persönlichst","e":"Das ist ein persönliches Geschenk.","en":"Det er en personlig gave."},
{"a":"praktisch","n":"praktisk","l":"A2","c":"praktischer","s":"praktischst","t":1,"e":"Der Rucksack ist praktisch.","en":"Sekken er praktisk."},
{"a":"privat","n":"privat","l":"B1","ng":1,"e":"Das ist eine private Frage.","en":"Det er et privat spørsmål."},
{"a":"pünktlich","n":"punktlig","l":"A2","c":"pünktlicher","s":"pünktlichst","e":"Der Bus ist pünktlich.","en":"Bussen er presis."},
{"a":"rau","n":"ru","l":"B1","c":"rauer","s":"rauest","e":"Seine Hände sind rau.","en":"Hendene hans er ru."},
{"a":"regnerisch","n":"regnfull","l":"A2","c":"regnerischer","s":"regnerischst","e":"Der Herbst ist regnerisch.","en":"Høsten er regnfull."},
{"a":"reich","n":"rik","l":"A2","c":"reicher","s":"reichst","e":"Er ist ein reicher Mann.","en":"Han er en rik mann."},
{"a":"richtig","n":"riktig","l":"A1","c":"richtiger","s":"richtigst","e":"Das ist die richtige Antwort.","en":"Det er det riktige svaret."},
{"a":"roh","n":"rå","l":"B1","c":"roher","s":"rohest","e":"Der Fisch ist roh.","en":"Fisken er rå."},
{"a":"rosa","n":"rosa","l":"A1","ind":1,"e":"Das ist ein rosa Kleid.","en":"Det er en rosa kjole."},
{"a":"rot","n":"rød","l":"A1","ng":1,"e":"Sie trägt ein rotes Kleid.","en":"Hun har på seg en rød kjole."},
{"a":"ruhig","n":"rolig","l":"A2","c":"ruhiger","s":"ruhigst","e":"Die Nacht war ruhig.","en":"Natten var rolig."},
{"a":"rund","n":"rund","l":"A2","ng":1,"e":"Der Tisch ist rund.","en":"Bordet er rundt."},
{"a":"salzig","n":"salt","l":"B1","c":"salziger","s":"salzigst","e":"Die Suppe ist zu salzig.","en":"Suppen er for salt."},
{"a":"sanft","n":"mild, myk","l":"B1","c":"sanfter","s":"sanftest","e":"Sie hat eine sanfte Stimme.","en":"Hun har en myk stemme."},
{"a":"sauber","n":"ren","l":"A2","c":"sauberer","s":"sauberst","t":1,"e":"Die Küche ist sauber.","en":"Kjøkkenet er rent."},
{"a":"sauer","n":"sur","l":"A2","c":"saurer","s":"sauerst","ps":"saur","e":"Die Zitrone ist sauer.","en":"Sitronen er sur."},
{"a":"scharf","n":"skarp, sterk (krydret)","l":"A2","c":"schärfer","s":"schärfst","cm":"sch‹ä›rfer","sm":"sch‹ä›rfst","e":"Das Essen ist scharf.","en":"Maten er sterk (krydret)."},
{"a":"schlau","n":"smart, lur","l":"A2","c":"schlauer","s":"schlauest","e":"Der Fuchs ist schlau.","en":"Reven er lur."},
{"a":"schlecht","n":"dårlig","l":"A1","c":"schlechter","s":"schlechtest","t":1,"e":"Das Wetter ist heute schlecht.","en":"Været er dårlig i dag."},
{"a":"schmal","n":"smal","l":"A2","c":"schmaler","s":"schmalst","c2":"schmäler","s2":"schmälst","e":"Der Weg ist schmal.","en":"Stien er smal."},
{"a":"schmutzig","n":"skitten","l":"A2","c":"schmutziger","s":"schmutzigst","t":1,"e":"Deine Schuhe sind schmutzig.","en":"Skoene dine er skitne."},
{"a":"schnell","n":"rask, fort","l":"A1","c":"schneller","s":"schnellst","t":1,"e":"Der Zug ist sehr schnell.","en":"Toget er veldig raskt."},
{"a":"schön","n":"vakker, fin","l":"A1","c":"schöner","s":"schönst","t":1,"e":"Du hast eine schöne Jacke.","en":"Du har en fin jakke."},
{"a":"schwach","n":"svak","l":"A2","c":"schwächer","s":"schwächst","cm":"schw‹ä›cher","sm":"schw‹ä›chst","e":"Ich fühle mich schwach.","en":"Jeg føler meg svak."},
{"a":"schwanger","n":"gravid","l":"B1","ng":1,"e":"Sie ist schwanger.","en":"Hun er gravid."},
{"a":"schwarz","n":"svart","l":"A1","ng":1,"e":"Ich habe eine schwarze Katze.","en":"Jeg har en svart katt."},
{"a":"schwer","n":"tung, vanskelig","l":"A1","c":"schwerer","s":"schwerst","t":1,"e":"Mein Rucksack ist schwer.","en":"Sekken min er tung."},
{"a":"schwierig","n":"vanskelig","l":"A2","c":"schwieriger","s":"schwierigst","t":1,"e":"Deutsch ist manchmal schwierig.","en":"Tysk er av og til vanskelig."},
{"a":"selten","n":"sjelden","l":"A2","c":"seltener","s":"seltenst","e":"Das ist ein seltener Vogel.","en":"Det er en sjelden fugl."},
{"a":"seltsam","n":"merkelig","l":"B1","c":"seltsamer","s":"seltsamst","e":"Er hat ein seltsames Hobby.","en":"Han har en merkelig hobby."},
{"a":"sicher","n":"sikker, trygg","l":"A2","c":"sicherer","s":"sicherst","e":"Hier ist es sicher.","en":"Her er det trygt."},
{"a":"sonnig","n":"solrik","l":"A2","c":"sonniger","s":"sonnigst","e":"Heute ist es sonnig.","en":"I dag er det solrikt."},
{"a":"spannend","n":"spennende","l":"A2","c":"spannender","s":"spannendst","e":"Der Krimi ist spannend.","en":"Krimmen er spennende."},
{"a":"spät","n":"sen","l":"A1","c":"später","s":"spätest","e":"Es ist schon spät.","en":"Det er allerede sent."},
{"a":"spitz","n":"spiss","l":"B1","c":"spitzer","s":"spitzest","e":"Das Messer ist spitz.","en":"Kniven er spiss."},
{"a":"stark","n":"sterk","l":"A1","c":"stärker","s":"stärkst","cm":"st‹ä›rker","sm":"st‹ä›rkst","t":1,"e":"Der Kaffee ist stark.","en":"Kaffen er sterk."},
{"a":"steil","n":"bratt","l":"B1","c":"steiler","s":"steilst","e":"Der Berg ist steil.","en":"Fjellet er bratt."},
{"a":"stolz","n":"stolt","l":"B1","c":"stolzer","s":"stolzest","e":"Ich bin stolz auf dich.","en":"Jeg er stolt av deg."},
{"a":"streng","n":"streng","l":"B1","c":"strenger","s":"strengst","e":"Mein Lehrer ist streng.","en":"Læreren min er streng."},
{"a":"stürmisch","n":"stormfull","l":"B1","c":"stürmischer","s":"stürmischst","e":"Die See ist stürmisch.","en":"Sjøen er stormfull."},
{"a":"süß","n":"søt","l":"A1","c":"süßer","s":"süßest","e":"Der Kuchen ist süß.","en":"Kaken er søt."},
{"a":"sympathisch","n":"sympatisk","l":"A2","c":"sympathischer","s":"sympathischst","e":"Sie ist sehr sympathisch.","en":"Hun er veldig sympatisk."},
{"a":"täglich","n":"daglig","l":"A2","ng":1,"e":"Das ist meine tägliche Routine.","en":"Det er min daglige rutine."},
{"a":"teuer","n":"dyr","l":"A1","c":"teurer","s":"teuerst","ps":"teur","t":1,"e":"Das Auto ist zu teuer.","en":"Bilen er for dyr."},
{"a":"tief","n":"dyp","l":"A2","c":"tiefer","s":"tiefst","t":1,"e":"Der See ist tief.","en":"Innsjøen er dyp."},
{"a":"toll","n":"kjempefin","l":"A1","c":"toller","s":"tollst","e":"Das ist eine tolle Idee!","en":"Det er en kjempefin idé!"},
{"a":"tot","n":"død","l":"A2","ng":1,"e":"Die Pflanze ist tot.","en":"Planten er død."},
{"a":"traurig","n":"trist","l":"A1","c":"trauriger","s":"traurigst","e":"Ich bin heute traurig.","en":"Jeg er trist i dag."},
{"a":"trocken","n":"tørr","l":"A2","c":"trockener","s":"trockenst","e":"Die Wäsche ist trocken.","en":"Klesvasken er tørr."},
{"a":"typisch","n":"typisk","l":"A2","c":"typischer","s":"typischst","e":"Das ist typisch deutsch.","en":"Det er typisk tysk."},
{"a":"üblich","n":"vanlig","l":"B1","c":"üblicher","s":"üblichst","e":"Das ist hier üblich.","en":"Det er vanlig her."},
{"a":"unbequem","n":"ukomfortabel","l":"B1","c":"unbequemer","s":"unbequemst","e":"Der Stuhl ist unbequem.","en":"Stolen er ukomfortabel."},
{"a":"unhöflich","n":"uhøflig","l":"B1","c":"unhöflicher","s":"unhöflichst","e":"Das war unhöflich.","en":"Det var uhøflig."},
{"a":"unmöglich","n":"umulig","l":"B1","c":"unmöglicher","s":"unmöglichst","e":"Das ist fast unmöglich.","en":"Det er nesten umulig."},
{"a":"unsympathisch","n":"usympatisk","l":"B1","c":"unsympathischer","s":"unsympathischst","e":"Der Mann war mir unsympathisch.","en":"Mannen var usympatisk for meg."},
{"a":"unterschiedlich","n":"ulik","l":"B1","c":"unterschiedlicher","s":"unterschiedlichst","e":"Wir haben unterschiedliche Meinungen.","en":"Vi har ulike meninger."},
{"a":"verheiratet","n":"gift","l":"A2","ng":1,"e":"Meine Eltern sind verheiratet.","en":"Foreldrene mine er gift."},
{"a":"verschieden","n":"forskjellig","l":"A2","c":"verschiedener","s":"verschiedenst","e":"Die Brüder sind sehr verschieden.","en":"Brødrene er veldig forskjellige."},
{"a":"viel","n":"mye, mange","l":"A1","c":"mehr","s":"meist","cm":"‹mehr›","sm":"‹meist›","nd":1,"e":"Ich habe viel Hausaufgaben.","en":"Jeg har mye lekser."},
{"a":"voll","n":"full","l":"A2","c":"voller","s":"vollst","t":1,"e":"Der Bus ist voll.","en":"Bussen er full."},
{"a":"vorsichtig","n":"forsiktig","l":"B1","c":"vorsichtiger","s":"vorsichtigst","e":"Fahr bitte vorsichtig!","en":"Kjør forsiktig, vær så snill!"},
{"a":"wach","n":"våken","l":"B1","c":"wacher","s":"wachst","e":"Ich bin schon wach.","en":"Jeg er allerede våken."},
{"a":"wahr","n":"sann","l":"A2","c":"wahrer","s":"wahrst","e":"Die Geschichte ist wahr.","en":"Historien er sann."},
{"a":"wahrscheinlich","n":"sannsynlig","l":"B1","c":"wahrscheinlicher","s":"wahrscheinlichst","e":"Das ist nicht sehr wahrscheinlich.","en":"Det er ikke veldig sannsynlig."},
{"a":"warm","n":"varm","l":"A1","c":"wärmer","s":"wärmst","cm":"w‹ä›rmer","sm":"w‹ä›rmst","t":1,"e":"Heute ist es warm.","en":"I dag er det varmt."},
{"a":"weich","n":"myk","l":"A2","c":"weicher","s":"weichst","e":"Das Bett ist weich.","en":"Sengen er myk."},
{"a":"weit","n":"vid, langt","l":"A2","c":"weiter","s":"weitest","e":"Der Weg ist weit.","en":"Veien er lang."},
{"a":"weiß","n":"hvit","l":"A1","ng":1,"e":"Der Schnee ist weiß.","en":"Snøen er hvit."},
{"a":"wenig","n":"lite, få","l":"A1","c":"weniger","s":"wenigst","cm":"‹weniger›","sm":"‹wenigst›","c2":"minder","s2":"minst","nd":1,"e":"Wir haben wenig Zeit.","en":"Vi har lite tid."},
{"a":"wertvoll","n":"verdifull","l":"B1","c":"wertvoller","s":"wertvollst","e":"Das ist ein wertvoller Ring.","en":"Det er en verdifull ring."},
{"a":"wichtig","n":"viktig","l":"A1","c":"wichtiger","s":"wichtigst","t":1,"e":"Das ist ein wichtiger Termin.","en":"Det er en viktig avtale."},
{"a":"windig","n":"vindfull","l":"A2","c":"windiger","s":"windigst","e":"Am Meer ist es windig.","en":"Ved havet er det vindfullt."},
{"a":"wirklich","n":"virkelig","l":"B1","c":"wirklicher","s":"wirklichst","e":"Das ist ein wirkliches Problem.","en":"Det er et virkelig problem."},
{"a":"wolkig","n":"skyet","l":"A2","c":"wolkiger","s":"wolkigst","e":"Morgen wird es wolkig.","en":"I morgen blir det skyet."},
{"a":"wunderbar","n":"fantastisk","l":"A2","c":"wunderbarer","s":"wunderbarst","e":"Das Wetter ist wunderbar.","en":"Været er fantastisk."},
{"a":"zart","n":"øm, myk","l":"B1","c":"zarter","s":"zartest","e":"Das Fleisch ist zart.","en":"Kjøttet er mørt."},
{"a":"zufrieden","n":"fornøyd","l":"A2","c":"zufriedener","s":"zufriedenst","e":"Ich bin zufrieden.","en":"Jeg er fornøyd."},
{"a":"zuverlässig","n":"pålitelig","l":"B1","c":"zuverlässiger","s":"zuverlässigst","e":"Er ist sehr zuverlässig.","en":"Han er veldig pålitelig."}
];
